///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CodedUiWordTest.Controllers.Mappings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DateiSystemDialog element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c71dbba8-56d1-47f5-89f1-8a9f31160cfe")]
    public partial class DateiSystemDialog : RepoGenBaseFolder
    {
        static DateiSystemDialog instance = new DateiSystemDialog();
        DateiSystemDialogFolders.DateiSystemFensterAppFolder _dateisystemfenster;
        RepoItemInfo _dateinameInfo;
        RepoItemInfo _offnenInfo;

        /// <summary>
        /// Gets the singleton class instance representing the DateiSystemDialog element repository.
        /// </summary>
        [RepositoryFolder("c71dbba8-56d1-47f5-89f1-8a9f31160cfe")]
        public static DateiSystemDialog Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DateiSystemDialog() 
            : base("DateiSystemDialog", "/", null, 0, false, "c71dbba8-56d1-47f5-89f1-8a9f31160cfe", ".\\RepositoryImages\\DateiSystemDialogc71dbba8.rximgres")
        {
            _dateisystemfenster = new DateiSystemDialogFolders.DateiSystemFensterAppFolder(this);
            _dateinameInfo = new RepoItemInfo(this, "Dateiname", "/form[@title='Öffnen']/combobox/text[@controlid='1148']", 30000, null, "b4001439-fe1a-4c51-bf4f-7b32e2bb7dd4");
            _offnenInfo = new RepoItemInfo(this, "Offnen", "/form[@title='Öffnen']/button[@text='Ö&ffnen']", 30000, null, "e9b1c6ec-d2d1-4fd4-be89-22ffdae57f2e");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c71dbba8-56d1-47f5-89f1-8a9f31160cfe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Dateiname item.
        /// </summary>
        [RepositoryItem("b4001439-fe1a-4c51-bf4f-7b32e2bb7dd4")]
        public virtual Ranorex.Text Dateiname
        {
            get
            {
                 return _dateinameInfo.CreateAdapter<Ranorex.Text>(true);
            }
        }

        /// <summary>
        /// The Dateiname item info.
        /// </summary>
        [RepositoryItemInfo("b4001439-fe1a-4c51-bf4f-7b32e2bb7dd4")]
        public virtual RepoItemInfo DateinameInfo
        {
            get
            {
                return _dateinameInfo;
            }
        }

        /// <summary>
        /// The Offnen item.
        /// </summary>
        [RepositoryItem("e9b1c6ec-d2d1-4fd4-be89-22ffdae57f2e")]
        public virtual Ranorex.Button Offnen
        {
            get
            {
                 return _offnenInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The Offnen item info.
        /// </summary>
        [RepositoryItemInfo("e9b1c6ec-d2d1-4fd4-be89-22ffdae57f2e")]
        public virtual RepoItemInfo OffnenInfo
        {
            get
            {
                return _offnenInfo;
            }
        }

        /// <summary>
        /// The DateiSystemFenster folder.
        /// </summary>
        [RepositoryFolder("edf5d3c2-2456-4f67-82a1-87bc1b37bcc7")]
        public virtual DateiSystemDialogFolders.DateiSystemFensterAppFolder DateiSystemFenster
        {
            get { return _dateisystemfenster; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DateiSystemDialogFolders
    {
        /// <summary>
        /// The DateiSystemFensterAppFolder folder.
        /// </summary>
        [RepositoryFolder("edf5d3c2-2456-4f67-82a1-87bc1b37bcc7")]
        public partial class DateiSystemFensterAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new DateiSystemFenster  folder.
            /// </summary>
            public DateiSystemFensterAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DateiSystemFenster", "/form[@title='Öffnen']", parentFolder, 30000, null, true, "edf5d3c2-2456-4f67-82a1-87bc1b37bcc7", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("edf5d3c2-2456-4f67-82a1-87bc1b37bcc7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("edf5d3c2-2456-4f67-82a1-87bc1b37bcc7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
