///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CodedUiWordTest.Controllers.Mappings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Edge element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ed0f350f-6026-4ee5-a12d-059cfa4faa35")]
    public partial class Edge : RepoGenBaseFolder
    {
        static Edge instance = new Edge();
        EdgeFolders.CurrencyplayerAppFolder _currencyplayer;
        EdgeFolders.OpenChangeAppFolder _openchange;
        RepoItemInfo _openchange2Info;
        RepoItemInfo _haupfensterInfo;

        /// <summary>
        /// Gets the singleton class instance representing the Edge element repository.
        /// </summary>
        [RepositoryFolder("ed0f350f-6026-4ee5-a12d-059cfa4faa35")]
        public static Edge Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Edge() 
            : base("Edge", "/", null, 0, false, "ed0f350f-6026-4ee5-a12d-059cfa4faa35", ".\\RepositoryImages\\Edgeed0f350f.rximgres")
        {
            _currencyplayer = new EdgeFolders.CurrencyplayerAppFolder(this);
            _openchange = new EdgeFolders.OpenChangeAppFolder(this);
            _openchange2Info = new RepoItemInfo(this, "OpenChange2", "/form[@title>'https://openexchangerates']/element/container[@accessiblerole='Document']/text/text[@accessiblename>'{  \"disclaimer\": \"Usage subject']", 30000, null, "f38faa2d-972b-496f-8589-2642476523f7");
            _haupfensterInfo = new RepoItemInfo(this, "HaupFenster", "/form[@title>'']/container[@classname='Intermediate D3D Window']", 30000, null, "4dac5a51-7462-45fb-bf72-bd8dd277eca3");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ed0f350f-6026-4ee5-a12d-059cfa4faa35")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The OpenChange2 item.
        /// </summary>
        [RepositoryItem("f38faa2d-972b-496f-8589-2642476523f7")]
        public virtual Ranorex.Text OpenChange2
        {
            get
            {
                 return _openchange2Info.CreateAdapter<Ranorex.Text>(true);
            }
        }

        /// <summary>
        /// The OpenChange2 item info.
        /// </summary>
        [RepositoryItemInfo("f38faa2d-972b-496f-8589-2642476523f7")]
        public virtual RepoItemInfo OpenChange2Info
        {
            get
            {
                return _openchange2Info;
            }
        }

        /// <summary>
        /// The HaupFenster item.
        /// </summary>
        [RepositoryItem("4dac5a51-7462-45fb-bf72-bd8dd277eca3")]
        public virtual Ranorex.Container HaupFenster
        {
            get
            {
                 return _haupfensterInfo.CreateAdapter<Ranorex.Container>(true);
            }
        }

        /// <summary>
        /// The HaupFenster item info.
        /// </summary>
        [RepositoryItemInfo("4dac5a51-7462-45fb-bf72-bd8dd277eca3")]
        public virtual RepoItemInfo HaupFensterInfo
        {
            get
            {
                return _haupfensterInfo;
            }
        }

        /// <summary>
        /// The Currencyplayer folder.
        /// </summary>
        [RepositoryFolder("5fbebbed-2da5-4f27-9ee1-1f2993321dc9")]
        public virtual EdgeFolders.CurrencyplayerAppFolder Currencyplayer
        {
            get { return _currencyplayer; }
        }

        /// <summary>
        /// The OpenChange folder.
        /// </summary>
        [RepositoryFolder("9ba10d80-6a7e-481b-8ba3-f4500a086e64")]
        public virtual EdgeFolders.OpenChangeAppFolder OpenChange
        {
            get { return _openchange; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class EdgeFolders
    {
        /// <summary>
        /// The CurrencyplayerAppFolder folder.
        /// </summary>
        [RepositoryFolder("5fbebbed-2da5-4f27-9ee1-1f2993321dc9")]
        public partial class CurrencyplayerAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Currencyplayer  folder.
            /// </summary>
            public CurrencyplayerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Currencyplayer", "/dom[@domain='api.currencylayer.com']", parentFolder, 30000, null, false, "5fbebbed-2da5-4f27-9ee1-1f2993321dc9", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5fbebbed-2da5-4f27-9ee1-1f2993321dc9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5fbebbed-2da5-4f27-9ee1-1f2993321dc9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The OpenChangeAppFolder folder.
        /// </summary>
        [RepositoryFolder("9ba10d80-6a7e-481b-8ba3-f4500a086e64")]
        public partial class OpenChangeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new OpenChange  folder.
            /// </summary>
            public OpenChangeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenChange", "/dom[@domain='https://openexchangerates.org/api/latest.json?app_id=1de86dfd996b4c9da20c0b3fa6eefaa4&amp;base=USD']", parentFolder, 30000, null, false, "9ba10d80-6a7e-481b-8ba3-f4500a086e64", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9ba10d80-6a7e-481b-8ba3-f4500a086e64")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9ba10d80-6a7e-481b-8ba3-f4500a086e64")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
